# **TIỀN XỬ LÝ DỮ LIỆU**

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.model_selection import train_test_split
from sklearn.metrics import explained_variance_score

##1.1 Tổng quan về bộ dữ liệu

 Đọc dữ liệu từ file CSV và hiện thị 5 dòng đầu bộ data

In [ ]:
file_path = '/content/ObesityDataSet_raw_and_data_sinthetic.csv'
df = pd.read_csv(file_path)
df.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

**Giải thích ý nghĩa 17 thuộc tính trong dữ liệu**
1. Gender: Giới tính của bệnh nhân.
2. Age : Tuổi của bênh nhân.
3. Height: Chiều cao của bênh nhân.
4. Weight: Cân nặng của bênh nhân.
5. family_history_with_overweight: Người thân trong gia đình có tiền sử béo phì không?
6. FAVC(Frequent consumption of high caloric food): Có thường xuyên ăn đồ ăn giàu năng lượng không?
7. FCVC(Frequency of Consumption of Vegetables): Có thường xuyên ăn rau, củ,... không?
8. NCP(Number of Main Meals): ăn bao nhiêu bữa mỗi ngày
9. CAEC(Consumption of Food Between Meals): Có ăn thêm đồ gì trong bữa ăn không?
10. SMOKE: Bệnh nhân có hút/không hút thuốc.
11. CH2O(Consumption of Water): Có thường xuyên uống nước không?
12. SCC(Calories Monitoring): Có tự giám sát lượng calories hằng ngày không?
13. FAF(Physical Activity Frequency): Có thường xuyên tập thể dục không?
14. TUE(Time Using Technology Devices): Có sử dụng nhiều thiết bị thông minh không?
16. CALC (Alcohol Consumption): Có thường xuyên uống rượu không?
17. MTRANS(Mode of Transportation): Phương tiện di chuyển hằng ngày
18. NObeyesdad: biến mục tiêu gồm 7 loại béo phì

Những thuộc tính này thường được sử dụng để phân tích và chẩn đoán béo phì ở mỗi bệnh nhân, đặc biệt trong việc phân biệt giữa các cấp độ béo phì dựa trên đặc điểm cơ thể, thói quen sinh hoạt hằng ngày của bệnh nhân.

Hiển thị kích thước của bảng dữ liệu

In [ ]:
df.shape

(2111, 17)

Hiển thị thông tin tóm tắt về DataFrame df. Cụ thể cung cấp các thông tin sau:

1. Số hàng và số cột của df
2. Tên cột và loại dữ liệu tương ứng của từng cột
3. Số lượng giá trị không bị thiếu của từng cột
4. Tổng dung lượng bộ nhớ mà df sử dụng

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             2111 non-null   float64
 1   Gender                          2111 non-null   object
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   CALC                            2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   SCC                             2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  family_history_with_overweight  2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CAEC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

Lệnh **df.isna().sum()** trong pandas được sử dụng để kiểm tra số lượng giá trị bị thiếu (NaN - Not a Number) trong mỗi cột của DataFrame df. Cụ thể:

df.isna(): Trả về một DataFrame với các giá

*   **df.isna()**: Trả về một DataFrame với các giá trị boolean, trong đó True chỉ ra giá trị bị thiếu (NaN) và False chỉ ra giá trị không bị thiếu.
*   **sum()**: Tổng hợp số lượng giá trị True (giá trị bị thiếu) trong mỗi cột. Kết quả là một danh sách cho biết số lượng giá trị thiếu trong từng cột của DataFrame.

In [ ]:
df.isna().sum()

Age                               0
Gender                            0
Height                            0
Weight                            0
CALC                              0
FAVC                              0
FCVC                              0
NCP                               0
SCC                               0
SMOKE                             0
CH2O                              0
family_history_with_overweight    0
FAF                               0
TUE                               0
CAEC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

Lệnh **df['NObeyesdad'].value_counts()** trong pandas được sử dụng để đếm số lượng các giá trị khác nhau trong cột NObeyesdad của DataFrame df.

 lệnh này sẽ trả về số lượng các mẫu tương ứng cho mỗi loại chẩn đoán. Kết quả sẽ là một bảng liệt kê số lượng các giá trị xuất hiện trong cột, giúp bạn hiểu rõ sự phân bố của các nhãn chẩn đoán trong dữ liệu.

In [ ]:
print(df['NObeyesdad'].value_counts())
df['NObeyesdad'].value_counts(True)

NObeyesdad
Obesity_Type_I         351
Obesity_Type_III       324
Obesity_Type_II        297
Overweight_Level_I     290
Overweight_Level_II    290
Normal_Weight          287
Insufficient_Weight    272
Name: count, dtype: int64

NObeyesdad
Obesity_Type_I         0.166272
Obesity_Type_III       0.153482
Obesity_Type_II        0.140692
Overweight_Level_I     0.137376
Overweight_Level_II    0.137376
Normal_Weight          0.135955
Insufficient_Weight    0.128849
Name: proportion, dtype: float64

##1.2 Mã hóa dữ liệu

### Sử dụng Binary Encoding để mã hóa các đặc trưng FAVC, SCC, SMOKE, family_history_with_overweight, Gender

Các đặc trưng FAVC, SCC, SMOKE và family_history_with_overweight được mã hóa bằng phương pháp Binary Encoding vì chúng chỉ chứa hai giá trị phân loại dạng Yes/No và female/mal. Việc sử dụng Binary Encoding giúp chuyển đổi dữ liệu sang dạng số một cách đơn giản, đồng thời vẫn giữ nguyên ý nghĩa của từng đặc trưng.

In [ ]:
df[['FAVC', 'SCC', 'SMOKE', 'family_history_with_overweight']].head()

  FAVC  SCC SMOKE family_history_with_overweight
0   no   no    no                            yes
1   no  yes   yes                            yes
2   no   no    no                            yes
3   no   no    no                             no
4   no   no    no                             no

In [ ]:
binary_cols = ['FAVC', 'SCC', 'SMOKE', 'family_history_with_overweight', 'Gender']

binary_mapping = {
    'yes': 1, 'no': 0,
    'Yes': 1, 'No': 0,
    'Male': 1, 'Female': 0
}

for col in binary_cols:
    df[col] = df[col].map(binary_mapping)

df[['FAVC', 'SCC', 'SMOKE', 'family_history_with_overweight']].head()

   FAVC  SCC  SMOKE  family_history_with_overweight
0     0    0      0                               1
1     0    1      1                               1
2     0    0      0                               1
3     0    0      0                               0
4     0    0      0                               0

### Sử dụng Ordinal Encoding để mã hóa các đặc trưng MTRANS,CALC, CAEC và NObeyesdad

Các đặc trưng MTRANS, CALC, CAEC và biến mục tiêu NObeyesdad được mã hóa bằng phương pháp Ordinal Encoding do các giá trị của chúng mang tính chất thứ bậc và có thể sắp xếp theo một mức độ nhất định.
- Đối với đặc trưng MTRANS, các giá trị gồm 'Walking', 'Bike', 'Public_Transportation', 'Motorbike', 'Automobile' được sắp xếp từ 0(thấp) → 4(cao) dựa trên mức độ tiêu hao năng lượng của cơ thể khi di chuyển, trong đó Walking tiêu tốn nhiều năng lượng nhất và Automobile tiêu tốn ít nhất.
- Đối với CALC và CAEC, các giá trị 'no', 'Sometimes', 'Frequently', 'Always' thể hiện mức độ tần suất tăng dần nên phù hợp để mã hóa theo thứ tự.
- Biến mục tiêu NObeyesdad gồm các mức 'Insufficient_Weight', 'Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II', 'Obesity_Type_I', 'Obesity_Type_II', 'Obesity_Type_III', được sắp xếp theo mức độ tăng dần của tình trạng cân nặng và béo phì.

In [ ]:
df[['MTRANS', 'CALC', 'CAEC', 'NObeyesdad']].head()

                  MTRANS        CALC       CAEC           NObeyesdad
0  Public_Transportation          no  Sometimes        Normal_Weight
1  Public_Transportation   Sometimes  Sometimes        Normal_Weight
2  Public_Transportation  Frequently  Sometimes        Normal_Weight
3                Walking  Frequently  Sometimes   Overweight_Level_I
4  Public_Transportation   Sometimes  Sometimes  Overweight_Level_II

In [ ]:
# MTRANS
mtrans_map = {
    'Automobile': 0,
    'Motorbike': 1,
    'Public_Transportation': 2,
    'Walking': 3,
    'Bike': 4
}
df['MTRANS'] = df['MTRANS'].map(mtrans_map)

# CALC, CAEC
ordinal_map = {
    'no': 0,
    'Sometimes': 1,
    'Frequently': 2,
    'Always': 3
}
df['CALC'] = df['CALC'].map(ordinal_map)
df['CAEC'] = df['CAEC'].map(ordinal_map)

# TARGET
target_map = {
    'Insufficient_Weight': 0,
    'Normal_Weight': 1,
    'Overweight_Level_I': 2,
    'Overweight_Level_II': 3,
    'Obesity_Type_I': 4,
    'Obesity_Type_II': 5,
    'Obesity_Type_III': 6
}
df['NObeyesdad'] = df['NObeyesdad'].map(target_map)
df[['MTRANS', 'CALC', 'CAEC', 'NObeyesdad']].head()

   MTRANS  CALC  CAEC  NObeyesdad
0       2     0     1           1
1       2     1     1           1
2       2     2     1           1
3       3     2     1           2
4       2     1     1           3

dữ liệu sau khi đã mã hóa xong

In [ ]:
data_encoded = df.copy()
data_encoded.to_csv('obesity_encoded.csv', index=False)
data_encoded.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,0,1.62,64.0,0,0,2.0,3.0,0,0,2.0,1,0.0,1.0,1,2,1
1,21.0,0,1.52,56.0,1,0,3.0,3.0,1,1,3.0,1,3.0,0.0,1,2,1
2,23.0,1,1.80,77.0,2,0,2.0,3.0,0,0,2.0,1,2.0,1.0,1,2,1
3,27.0,1,1.80,87.0,2,0,3.0,3.0,0,0,2.0,0,2.0,0.0,1,3,2
4,22.0,1,1.78,89.8,1,0,2.0,1.0,0,0,2.0,0,0.0,0.0,1,2,3